clc
clear all
close all

matNames={ 'RecognitionAudio.mat' ; ... 
           'RecognitionVideo.mat' ; ...
           'RecognitionFused.mat' ; ...
           'RecognitionDecFused.mat' ; ...
           'CascadeRecognitionAudio.mat' ; ... 
           'CascadeRecognitionVideo.mat' ; ...
           'CascadeRecognitionFused.mat' ; ...
           'CascadeRecognitionDecFused.mat' };
       
figure('Position',[50 50 1000 600]);
for i=1:8
    load(['EXPproper/' matNames{i}],'ConfusionMatrix');
    subplot(2,4,i);
    plotConfusionMat;
end